version: "3.8"

services:
  nginx:
    image: nginx:1.27
    container_name: sa-nginx
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - ../web:/var/www
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go

  go:
    build:
      context: ..
      dockerfile: deploy/go/Dockerfile
    container_name: sa-go
    volumes:
      - ../web:/var/www/
    working_dir: /var/www/
    depends_on:
      - postgres
      - redis
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres_sa
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      REDIS_HOST: redis

  postgres:
    image: postgres:15
    container_name: sa-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres_sa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: sa-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
